controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: ilchenko.m.a
 * Date: 12.08.2019
 * Time: 16:45
 */

namespace app\controllers;

use app\models\search\ProductSearch;
use Yii;
use app\models\elastic\Product;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class ProductController extends Controller
{

    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Запись обновлена');
            return $this->render('update', [
                'model' => $model
            ]);
        } else {
            return $this->render('update', [
                'model' => $model
            ]);
        }
    }

    /**
     * @return \yii\web\Response
     */
    public function actionDeleteAll()
    {
        Product::deleteIndex();
        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @return Product|array|mixed|null|\yii\elasticsearch\ActiveRecord
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/product/_form.php
<?php

use app\models\elastic\Manufacturer;
use app\models\elastic\Stock;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use kartik\grid\GridView;
use yii\data\ArrayDataProvider;

/**
 * @var $this \yii\web\View
 * @var $model \app\models\elastic\Product
 */

$this->title = $model->name;
?>

<?php $form = ActiveForm::begin([
    'class' => 'row'
]) ?>

<div class="row">
    <div class="col-md-6">
        <?= $form->field($model, 'sid')->textInput() ?>
    </div>
    <div class="col-md-6">
        <?= $form->field($model->manufacturer, 'name')->textInput() ?>
    </div>
</div>

<?= $form->field($model, 'name')->textInput() ?>

<?= GridView::widget([
    'dataProvider' => new ArrayDataProvider(['allModels' => $model->stockProducts]),
    'pjax'=>true,
    'columns' => [
        ['class' => 'kartik\grid\SerialColumn'],
//            [
//                'attribute' => 'product',
//                'content' => function(StockProduct $model){
//                    return Html::a($model->product_id, ['product/update', ['id' => $model->elProduct->_id]]);
//                }
//            ],
        'amount',
        'price:currency',
        'stock.name',
        'stock.organization.name',
        ['class' => 'kartik\grid\ActionColumn'],
    ]
])?>

<div class="form-group">
    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
</div>

<?php ActiveForm::end() ?>

views/product/index.php
<?php

use app\models\elastic\Organization;
use kartik\grid\GridView;
use app\models\elastic\Product;

$this->title = 'Products';

/**
 * @var $this yii\web\View
 * @var \yii\elasticsearch\ActiveDataProvider $dataProvider
 * @var \app\models\search\ProductSearch $searchModel
 */
?>
<?php print_r(Product::find()->count());?>

<div class="product-index">
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'pjax'=>true,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],
            'primaryKey',
//            [
//                'attribute' => 'manufacturer.name',
//                'content' => function(Product $product){
//                    return $product->manufacturer->name;
//                }
//            ],
            'sid',
            'name',
//            [
//                'attribute' => 'count',
//                'content' => function(Product $model){
//                    return $model->getStockProducts()->count();
//                }
//            ],
            [
                'class' => 'kartik\grid\ActionColumn',
            ],
        ]
    ])?>
</div>

views/product/update.php
<?php

/**
 * @var $this \yii\web\View
 * @var $model \app\models\elastic\Product
 */
?>
<div class="stock_product-update">
    <?= $this->render('_form', compact('model'))?>
</div>